In [11]:
import numpy as np
import pandas as pd

## Datatypes & Attributes 

In [5]:
# Numpay main datatype is ndarray (n-dimensional array)
a1 = np.array([1, 2, 3])
print(type(a1))  # <class 'numpy.ndarray'>
print(a1)

a2 = np.array([[1, 2.0, 3.3], [4, 5, 6]])
print(a2)

print(a2.dtype)  # float64

# a3 3 dimensional array 1 to 18
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]], dtype='int32')
print(a3)
print(a3.dtype)  # int32

<class 'numpy.ndarray'>
[1 2 3]
[[1.  2.  3.3]
 [4.  5.  6. ]]
float64
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
int32


In [ ]:
# Numpy Attributes

a1.shape  #! returns a tuple with array dimensions


(3,)

In [ ]:
a1.ndim , a2.ndim , a3.ndim  #! returns number of dimensions

(1, 2, 3)

In [9]:
# data types
a1.dtype, a2.dtype, a3.dtype  #! returns data type of array elements

(dtype('int64'), dtype('float64'), dtype('int32'))

In [10]:
# size 
a1.size, a2.size, a3.size  #! returns total number of elements in the array

(3, 6, 18)

In [ ]:
# Create a DataFrame from Numpy Array

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.0

## 2.Creating Numpy Arrays

In [19]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [25]:
ones = np.ones((2,3)) # 2 rows and 3 columns of ones
ones
type(ones)  #! numpy.ndarray

numpy.ndarray

In [26]:
zeros = np.zeros((2,3)) # 2 rows and 3 columns of zeros
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])