In [11]:
import numpy as np
import pandas as pd

## Datatypes & Attributes 

In [5]:
# Numpay main datatype is ndarray (n-dimensional array)
a1 = np.array([1, 2, 3])
print(type(a1))  # <class 'numpy.ndarray'>
print(a1)

a2 = np.array([[1, 2.0, 3.3], [4, 5, 6]])
print(a2)

print(a2.dtype)  # float64

# a3 3 dimensional array 1 to 18
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]], dtype='int32')
print(a3)
print(a3.dtype)  # int32

<class 'numpy.ndarray'>
[1 2 3]
[[1.  2.  3.3]
 [4.  5.  6. ]]
float64
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
int32


In [ ]:
# Numpy Attributes

a1.shape  #! returns a tuple with array dimensions


(3,)

In [ ]:
a1.ndim , a2.ndim , a3.ndim  #! returns number of dimensions

(1, 2, 3)

In [9]:
# data types
a1.dtype, a2.dtype, a3.dtype  #! returns data type of array elements

(dtype('int64'), dtype('float64'), dtype('int32'))

In [10]:
# size 
a1.size, a2.size, a3.size  #! returns total number of elements in the array

(3, 6, 18)

In [ ]:
# Create a DataFrame from Numpy Array

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.0

## 2.Creating Numpy Arrays

In [19]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [25]:
ones = np.ones((2,3)) # 2 rows and 3 columns of ones
ones
type(ones)  #! numpy.ndarray

numpy.ndarray

In [26]:
zeros = np.zeros((2,3)) # 2 rows and 3 columns of zeros
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
range_array = np.arange(0, 10, 2)  #! start, stop, step
range_array

array([0, 2, 4, 6, 8])

In [36]:
random_array = np.random.randint(0, 10, size=(3, 5 ))  # random integers between 0 and 10 with shape 3x5 (3 rows and 5 columns)
random_array


array([[8, 3, 9, 1, 3],
       [9, 6, 4, 2, 1],
       [9, 3, 3, 1, 0]], dtype=int32)

In [ ]:

random_array.size # total number of elements in the array

15

In [43]:
random_array.shape # shape of the array (rows, columns)

(3, 5)

In [44]:
np.random.random((3,4))  # random floats between 0 and 1 with shape 3x4

array([[0.70414027, 0.26600426, 0.24943407, 0.4526769 ],
       [0.18094394, 0.1785018 , 0.16834887, 0.46890691],
       [0.02605839, 0.93657476, 0.05011535, 0.92298693]])

In [54]:
# Pseudo-random numbers
np.random.seed(seed=0)  #! set the seed for reproducibility 

#! Now random numbers generated will be the same each time
#! beacause we set the seed to 0

random_array_X = np.random.randint(10, size=(5,3)) # 5 rows and 3 columns of random integers between 0 and 10
random_array_X

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

In [57]:
np.random.seed(seed=0)  #! reset the seed to 0
random_array_Y = np.random.random((5,3)) # 5 rows and 3 columns of random floats between 0 and 1
random_array_Y

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606]])