In [1]:
import numpy as np
import pandas as pd

## Datatypes & Attributes 

In [2]:
# Numpay main datatype is ndarray (n-dimensional array)
a1 = np.array([1, 2, 3])
print(type(a1))  # <class 'numpy.ndarray'>
print(a1)

a2 = np.array([[1, 2.0, 3.3], [4, 5, 6]])
print(a2)

print(a2.dtype)  # float64

# a3 3 dimensional array 1 to 18
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]], dtype='int32')
print(a3)
print(a3.dtype)  # int32

<class 'numpy.ndarray'>
[1 2 3]
[[1.  2.  3.3]
 [4.  5.  6. ]]
float64
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
int32


In [ ]:
# Numpy Attributes

a1.shape  #! returns a tuple with array dimensions


(3,)

In [ ]:
a1.ndim , a2.ndim , a3.ndim  #! returns number of dimensions

(1, 2, 3)

In [9]:
# data types
a1.dtype, a2.dtype, a3.dtype  #! returns data type of array elements

(dtype('int64'), dtype('float64'), dtype('int32'))

In [10]:
# size 
a1.size, a2.size, a3.size  #! returns total number of elements in the array

(3, 6, 18)

In [ ]:
# Create a DataFrame from Numpy Array

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.0

## 2.Creating Numpy Arrays

In [19]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [25]:
ones = np.ones((2,3)) # 2 rows and 3 columns of ones
ones
type(ones)  #! numpy.ndarray

numpy.ndarray

In [26]:
zeros = np.zeros((2,3)) # 2 rows and 3 columns of zeros
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
range_array = np.arange(0, 10, 2)  #! start, stop, step
range_array

array([0, 2, 4, 6, 8])

In [36]:
random_array = np.random.randint(0, 10, size=(3, 5 ))  # random integers between 0 and 10 with shape 3x5 (3 rows and 5 columns)
random_array


array([[8, 3, 9, 1, 3],
       [9, 6, 4, 2, 1],
       [9, 3, 3, 1, 0]], dtype=int32)

In [ ]:

random_array.size # total number of elements in the array

15

In [43]:
random_array.shape # shape of the array (rows, columns)

(3, 5)

In [44]:
np.random.random((3,4))  # random floats between 0 and 1 with shape 3x4

array([[0.70414027, 0.26600426, 0.24943407, 0.4526769 ],
       [0.18094394, 0.1785018 , 0.16834887, 0.46890691],
       [0.02605839, 0.93657476, 0.05011535, 0.92298693]])

In [54]:
# Pseudo-random numbers
np.random.seed(seed=0)  #! set the seed for reproducibility 

#! Now random numbers generated will be the same each time
#! beacause we set the seed to 0

random_array_X = np.random.randint(10, size=(5,3)) # 5 rows and 3 columns of random integers between 0 and 10
random_array_X

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]], dtype=int32)

In [57]:
np.random.seed(seed=0)  #! reset the seed to 0
random_array_Y = np.random.random((5,3)) # 5 rows and 3 columns of random floats between 0 and 1
random_array_Y

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606]])

## 3. Viewing arrays and matrices

In [58]:
np.unique(random_array_X)  #! unique values in the array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [59]:
a1

array([1, 2, 3])

In [60]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6. ]])

In [61]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)

In [62]:
a1[0]

np.int64(1)

In [63]:
a2[0]

array([1. , 2. , 3.3])

In [ ]:
a3.shape # shape of the 3D array (2 matrices, 2 rows, 3 columns)

(3, 2, 3)

In [66]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [67]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)

In [68]:
a3.shape  # shape of the 3D array (2 matrices, 2 rows, 3 columns)

(3, 2, 3)

In [70]:
a3[:2, :2, :2]  # first 2 matrices, first 2 rows, first 2 columns

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]], dtype=int32)

In [73]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))  # 4D array
a4

array([[[[3, 8, 2, 8, 4],
         [3, 0, 4, 3, 6],
         [9, 8, 0, 8, 5],
         [9, 0, 9, 6, 5]],

        [[3, 1, 8, 0, 4],
         [9, 6, 5, 7, 8],
         [8, 9, 2, 8, 6],
         [6, 9, 1, 6, 8]],

        [[8, 3, 2, 3, 6],
         [3, 6, 5, 7, 0],
         [8, 4, 6, 5, 8],
         [2, 3, 9, 7, 5]]],


       [[[3, 4, 5, 3, 3],
         [7, 9, 9, 9, 7],
         [3, 2, 3, 9, 7],
         [7, 5, 1, 2, 2]],

        [[8, 1, 5, 8, 4],
         [0, 2, 5, 5, 0],
         [8, 1, 1, 0, 3],
         [8, 8, 4, 4, 0]],

        [[9, 3, 7, 3, 2],
         [1, 1, 2, 1, 4],
         [2, 5, 5, 5, 2],
         [5, 7, 7, 6, 1]]]], dtype=int32)

In [74]:
# Get the first 4 numbers of the inner most array
a4[0, 0, 0, :4]  # first matrix,

array([3, 8, 2, 8], dtype=int32)

## 4. Manipulating and comparing arrays

### Arithmetic Operations (+,-,*,/)

In [ ]:
a1 


array([1, 2, 3])

In [ ]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a1 + ones

array([[2., 3., 4.],
       [2., 3., 4.]])

In [85]:
# (-)
a1 - ones

# (*)
a1 * ones

# (/)
a1 / ones

array([[1., 2., 3.],
       [1., 2., 3.]])

In [87]:
a2 * a3 # 

array([[[  1. ,   4. ,   9.9],
        [ 16. ,  25. ,  36. ]],

       [[  7. ,  16. ,  29.7],
        [ 40. ,  55. ,  72. ]],

       [[ 13. ,  28. ,  49.5],
        [ 64. ,  85. , 108. ]]])

### Aggregation (min, max, mean, sum, etc.)
Aggregation = performing the same operation on a number of things.

In [89]:
listy_list = [1, 2, 3]
type(listy_list)

list

In [90]:
sum(listy_list)

6

In [91]:
a1

array([1, 2, 3])

In [92]:
np.sum(a1)

np.int64(6)

In [93]:
# Use python's method on Python datatypes  😏
#  Numpy's method on Numpy arrays ✌️

In [94]:
# Create a massive NumPy array
massive_array = np.random.random(1000000)
massive_array.size

1000000

In [95]:
massive_array[:10]

array([0.31179588, 0.69634349, 0.37775184, 0.17960368, 0.02467873,
       0.06724963, 0.67939277, 0.45369684, 0.53657921, 0.89667129])

In [96]:
%timeit sum(massive_array)  # Python sum() function
%timeit np.sum(massive_array)  # Numpy sum() function

95 ms ± 3.49 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.57 ms ± 44.1 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [97]:
np.mean(a2)

np.float64(3.5500000000000003)

In [98]:
np.mean(massive_array)

np.float64(0.5003861313217297)

In [100]:
np.min(a2)


np.float64(1.0)

In [101]:
np.max(a2)

np.float64(6.0)

In [ ]:
np.std(a2)  # standard deviation in simple words means how spread out the values are from the mean and how much they deviate from it 

In [3]:
# Demo of standard deviation and variance
high_var_array = np.array([1, 100, 200, 300, 4000, 5000])
low_var_array = np.array([10, 12, 14, 16, 18])

In [6]:
np.var(high_var_array), np.var(low_var_array)    # variance


(np.float64(4296133.472222221), np.float64(8.0))

In [8]:
np.std(high_var_array), np.std(low_var_array) # standard deviation

(np.float64(2072.711623024829), np.float64(2.8284271247461903))

In [9]:
%matplotlib inline
import matplotlib.pyplot as plt # pyright: ignore[reportMissingModuleSource]
plt.hist(high_var_array)
plt.hist(low_var_array)
plt.show()

ModuleNotFoundError: No module named 'matplotlib'